debug: true
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://172.16.87.26:3370/wec_local_asset
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

